# Sheldon configuration for zsh
# https://github.com/rossmacarthur/sheldon

shell = "zsh"

# Deferred loading support
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# PATH configuration (must be loaded first for aqua-managed tools)
[plugins.local-path]
local = "~/.config/zsh"
use = ["00_path.zsh"]

# Starship prompt initialization
[plugins.starship]
inline = 'eval "$(starship init zsh)"'
hooks.pre = 'export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"'

# direnv hook (deferred)
[plugins.direnv]
inline = 'zsh-defer eval "$(direnv hook zsh)"'

# Custom completions
[plugins.local-completions]
local = "~/.config/zsh/completions"
apply = ["fpath"]

# Aqua CLI completions generator (runs in background, see README.md)
[plugins.aqua-completions]
local = "~/.config/sheldon/aqua-completions"
use = ["init.zsh"]
apply = ["defer"]

# fzf color scheme (Akari)
[plugins.akari-fzf]
github = "cappyzawa/akari-fzf"
use = ["akari-night.sh"]

# fzf-tab: Tab completion with fzf
# Must be loaded after compinit, before zsh-autosuggestions
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
# renovate: depName=Aloxaf/fzf-tab
tag = "v1.2.0"

# fzf history search (Ctrl+R)
[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"
hooks.pre = '''
export ZSH_FZF_HISTORY_SEARCH_REMOVE_DUPLICATES=1
export ZSH_FZF_HISTORY_SEARCH_DATES_IN_SEARCH=1
'''

# Syntax highlighting (deferred)
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
# renovate: depName=zsh-users/zsh-syntax-highlighting
tag = "0.8.0"
apply = ["defer"]

# zsh-syntax-highlighting theme (Akari)
# Must be loaded after zsh-syntax-highlighting
[plugins.akari-zsh]
github = "cappyzawa/akari-zsh"
use = ["akari-night.zsh"]

# Autosuggestions (deferred, must be after fzf-tab)
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
# renovate: depName=zsh-users/zsh-autosuggestions
tag = "v0.7.1"
apply = ["defer"]

# Local configuration files (immediate loading)
[plugins.local]
local = "~/.config/zsh"
use = ["*.zsh", "!*.defer.zsh", "!00_path.zsh"]

# Local configuration files (deferred loading)
[plugins.local-defer]
local = "~/.config/zsh"
use = ["*.defer.zsh"]
apply = ["defer"]

# Custom templates
[templates]
defer = '{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}'
fpath = 'fpath=( "{{ dir }}" $fpath )'
