[aws]
disabled = true

[battery]
disabled = true

[character]
symbol = "$"
use_symbol_for_status = false
# Green
style_success = "bold #98c379"
# Light Red
style_failure = "bold #e06c75"

[cmd_duration]
# Light Yellow
style = "#e5c07b"

[directory]
truncation_length = 3
# Blue
style = "#61afef"

[env_var]
# TODO
# Green
style = "#98c379"

[git_branch]
# Light Red
style = "#e06c75"

[git_state]
disabled = true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
added = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
show_sync_count = true
# Light Red
style = "#e06c75"

[golang]
# Cyan
style = "#56b6c2"

[hostname]
# Green
style = "#98c379"

[jobs]
# Blue
style = "#61afef"

[kubernetes]
symbol = "âˆ "
# Cyan
style = "#56b6c2"
disabled = true

[line_break]
disabled = false

[nix_shell]
disabled = true

[java]
# Dark Red
style = "#be5046"

[nodejs]
symbol = "ğŸ¤– "
# Green
style = "#98c379"

[package]
symbol = "ğŸ "
# Dark Red
style = "#be5046"

[python]
# Light Yellow
style = "#e5c07b"

[ruby]
# Dark Red
style = "#be5046"

[rust]
symbol = "âš™ï¸ "
# Dark Yellow
style = "#d19a66"

[time]
disabled = true

[username]
disabled = false
# Light Yellow
style_user = "#e5c07b"
