# Replace the "âœ" symbol in the prompt with "â¯"
[character]      # The name of the module we are confguring is "character"
symbol = "$"     # The "symbol" segment is being set to "â¯"
error_symbol = "âš¡ï¸"
use_symbol_for_status = true
# Green
style = "bold #98c379"

[cmd_duration]
# Light Yellow
style = "#e5c07b"

[battery]
disabled = true

[directory]
truncation_length = 3
# Blue
style = "#61afef"

[git_branch]
# Light Red
style = "#e06c75"

[git_state]
# Light Red
style = "#e06c75"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
added = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
show_sync_count = true
# Light Red
style = "#e06c75"

[package]
symbol = "ğŸ "
# Dark Red
style = "#be5046"

[nodejs]
symbol = "ğŸ¤– "
# Green
style = "#98c379"

[rust]
symbol = "âš™ï¸ "
# Dark Yellow
style = "#d19a66"

[golang]
# Cyan
style = "#56b6c2"

[java]
# Dark Red
style = "#be5046"


[username]
disabled = false
