# Replace the "âœ" symbol in the prompt with "â¯"
[character]      # The name of the module we are confguring is "character"
symbol = "$"     # The "symbol" segment is being set to "â¯"
error_symbol = "âœ—"
use_symbol_for_status = true

[battery]
disabled = true

[directory]
truncation_length = 3

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
added = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[package]
symbol = "ğŸ "

[nodejs]
symbol = "ğŸ¤– "

[rust]
symbol = "âš™ï¸ "

[username]
disabled = false
