[prompt]
add_newline = true

[aws]
disabled = true

[battery]
disabled = true

[character]
symbol = "$"
use_symbol_for_status = false
# Green
style_success = "bold #98c379"
# Light Red
style_failure = "bold #e06c75"

[cmd_duration]
# Light Yellow
style = "#e5c07b"

[conda]
# Green
style = "#98c379"

[directory]
truncation_length = 3
# Cyan
style = "bold #56b6c2"

[dotnet]
disabled = true

[env_var]
disabled = true

[git_branch]
# Light Red
style = "#e06c75"

[git_state]
disabled = true

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
stashed_count.enabled = true
show_sync_count = true
# Light Red
style = "#e06c75"

[golang]
# Cyan
style = "#56b6c2"

[hostname]
# Green
style = "#98c379"

[jobs]
# Blue
style = "#61afef"

[kubernetes]
symbol = "âˆ "
# Blue
style = "#61afef"
disabled = false

[line_break]
disabled = false

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[java]
# Dark Red
style = "#be5046"

[nodejs]
symbol = "ğŸ¤– "
# Green
style = "#98c379"

[package]
symbol = "ğŸ "
# Dark Red
style = "#be5046"

[python]
# Light Yellow
style = "#e5c07b"

[ruby]
# Dark Red
style = "#be5046"

[rust]
symbol = "âš™ï¸ "
# Dark Yellow
style = "#d19a66"

[time]
disabled = true

[username]
disabled = false
# Light Yellow
style_user = "#e5c07b"
