# Akari Dawn â€” A light palette inspired by Japanese alleys lit by round lanterns.

[colors.primary]
background = "#E4DED6"
foreground = "#1A1816"

[colors.cursor]
text = "#E4DED6"
cursor = "#8A4530"

[colors.selection]
text = "#1A1816"
background = "#D7C5B1"

[colors.normal]
black   = "#1A1816"
red     = "#6A2828"
green   = "#3A5830"
yellow  = "#B07840"
blue    = "#304050"
magenta = "#806080"
cyan    = "#305858"
white   = "#E4DED6"

[colors.bright]
black   = "#514B45"
red     = "#3E1717"
green   = "#20301A"
yellow  = "#78522C"
blue    = "#131A20"
magenta = "#543F54"
cyan    = "#152727"
white   = "#D0C5B7"
