[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 22.0

[font.bold]
family = "Moralerspace Argon NF"
style = "Bold"

[font.italic]
family = "Moralerspace Argon NF"
style = "Italic"

[font.normal]
family = "Moralerspace Argon NF"
style = "Regular"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-i", "-c", "tmux new-session -A -s zzz"]

[window]
decorations = "full"
dynamic_padding = true
option_as_alt = "Both"
# startup_mode = "Fullscreen"

[window.padding]
x = 5
y = 5

[general]
import = ["rose-pine.toml"]

[terminal]

[keyboard]
bindings = []
