# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'akari-night'
add_newline = true

[palettes.tokyonight]
background = '#1a1b26'
foreground = '#c0caf5'
current_line = '#283457'
primary = '#1E1F29'
box = '#283457'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
orange = '#ff9e64'
pink = '#bb9af7'
purple = '#9d7cd8'
red = '#f7768e'
yellow = '#e0af68'

[palettes.akari-night]
# Standard ANSI colors
black = '#12100E'         # ansi.black
red = '#C84C32'           # ansi.red
green = '#7FAF6A'         # ansi.green
yellow = '#D4A05A'        # ansi.yellow
blue = '#5A6F82'          # ansi.blue
purple = '#7C6A8A'        # ansi.magenta
cyan = '#6F8F8A'          # ansi.cyan
white = '#E6DED3'         # ansi.white

# Bright variants
bright-black = '#2E3543'  # ansi.bright.black
bright-red = '#D65A3A'    # ansi.bright.red
bright-green = '#8FC57A'  # ansi.bright.green
bright-yellow = '#F08A5D' # ansi.bright.yellow
bright-blue = '#6F879A'   # ansi.bright.blue
bright-purple = '#9A8FB3' # ansi.bright.magenta
bright-cyan = '#8FB8B0'   # ansi.bright.cyan
bright-white = '#F2ECE4'  # ansi.bright.white

[palettes.akari-dawn]
# Standard ANSI colors
black = '#1A1816'         # ansi.black
red = '#B04030'           # ansi.red
green = '#3A5830'         # ansi.green
yellow = '#B07840'        # ansi.yellow
blue = '#304050'          # ansi.blue
purple = '#806080'        # ansi.magenta
cyan = '#305858'          # ansi.cyan
white = '#F4F0EA'         # ansi.white

# Bright variants
bright-black = '#3A3E48'  # ansi.bright.black
bright-red = '#C04838'    # ansi.bright.red
bright-green = '#70A868'  # ansi.bright.green
bright-yellow = '#D09060' # ansi.bright.yellow
bright-blue = '#4060A0'   # ansi.bright.blue
bright-purple = '#705868' # ansi.bright.magenta
bright-cyan = '#306868'   # ansi.bright.cyan
bright-white = '#0A0808'  # ansi.bright.white

[os]
disabled = true

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[kubernetes]
symbol = '󱃾 '
disabled = false

[docker_context]
disabled = true

[directory]
# home_symbol = " ~/"
# truncation_symbol = ' '
truncation_length = 2
read_only = '󱧵 '
read_only_style = ''

[git_branch]
symbol = ' '

[git_status]
conflicted = '='
up_to_date = ''
untracked = '?${count}'
stashed = '\$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»'
deleted = '✘'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[aws]
disabled = true

[nodejs]
symbol = '󰎙 '

[dotnet]
symbol = ' '

[python]
symbol = ' '

[java]
symbol = ' '

[c]
symbol = ' '

[golang]
symbol = " "

[lua]
symbol = ' '
disabled = true

[terraform]
symbol = '󱁢 '

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500

[shell]
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
fish_indicator = 'fish'
disabled = true

[time]
time_format = '%H:%M'
disabled = true

[username]
show_always = true
disabled = true

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vicmd_symbol = "[](bold yellow)"
